language: python
python:
  - "2.7"
# Need mongodb for testing
services: mongodb
# command to install dependencies
install: 
  - pip install -r requirements_for_tests.txt --use-mirrors
# command to run tests
env:
  - SKIP_VIRUS_SCAN=1 MONGO_REPLICA_SET=''
script:
  - ./run_tests.sh
after_script:
  - coveralls
branches:
  except:
    - release
notifications:
  email: false
