language: python
python:
  - "2.6"
  - "2.7"
matrix:
  allow_failures:
    - python: "2.6"
# Need mongodb for testing
services: mongodb
# command to install dependencies
install: 
  - pip install -q -r requirements_for_tests.txt --use-mirrors
# command to run tests
env:
  - SKIP_SPLINTER_TESTS=1 SKIP_VIRUS_SCAN=1
script:
  - ./run_tests.sh
after_script:
  - coveralls
branches:
  except:
    - release
notifications:
  email: false
